

export interface Transaction {
  id: string;
  amount: number;
  merchant: string;
  category: string;
  date: string; // ISO string format
  isRecurring?: boolean;
  recurrencePeriod?: 'daily' | 'weekly' | 'monthly' | 'yearly' | null;
  nextDueDate?: string | null; // ISO string format
  isAutoGenerated?: boolean;
  type?: 'income' | 'expense';
}

export interface Budget {
  id: string;
  category: string;
  target: number;
}

export interface Goal {
  id:string;
  name: string;
  targetAmount: number;
  currentAmount: number;
  allocation: number; // Percentage (0-100)
}

export interface Achievement {
  id: string;
  name: string;
  description: string;
  achieved: boolean;
}

export interface Profile {
  firstName: string;
  lastName: string;
  college: string;
  degree: string;
  graduationYear: number;
}

export interface Testimonial {
    id: string;
    firstName: string;
    lastName: string;
    message: string;
    createdAt: any; // Firestore Timestamp
}


export interface AppData {
  transactions: Transaction[];
  budgets: Budget[];
  goals: Goal[];
  achievements: Achievement[];
  profile: Profile;
  lastLoginDate: string;
  dailyStreak: number;
}
